from __future__ import annotations

from pathlib import Path

from repo_brain.models import RepoMap, ScanResult


def write_markdown(brain_dir: Path, result: ScanResult, repo_map: RepoMap) -> Path:
    brain_dir.mkdir(parents=True, exist_ok=True)
    out = brain_dir / "REPO_MAP.md"

    classes = [s for s in result.symbols if s.symbol_type == "class"]
    functions = [s for s in result.symbols if s.symbol_type in ("function", "async_function")]
    test_files = [f for f in result.files if f.is_test]

    lines: list[str] = []

    lines.append("# Repository Map\n")
    lines.append("## Summary\n")
    lines.append(f"- Python files: {repo_map.python_file_count}")
    lines.append(f"- Classes: {len(classes)}")
    lines.append(f"- Functions: {len(functions)}")
    lines.append(f"- FastAPI routes: {len(result.routes)}")
    lines.append(f"- Test files: {len(test_files)}")
    lines.append("")

    lines.append("## Top-level Modules\n")
    for mod in repo_map.top_level_modules:
        lines.append(f"- `{mod}`")
    lines.append("")

    lines.append("## FastAPI Routes\n")
    lines.append("| Method | Path | Handler | File |")
    lines.append("|--------|------|---------|------|")
    for route in sorted(result.routes, key=lambda r: (r.path, r.method)):
        lines.append(
            f"| `{route.method.upper()}` | `{route.path}` | `{route.function_name}` | `{route.file_path}` |"
        )
    lines.append("")

    lines.append("## Important Files\n")
    for f in result.files:
        if not f.is_test:
            lines.append(f"- `{f.path}` ({f.line_count} lines)")
    lines.append("")

    lines.append("## Tests\n")
    for t in result.tests:
        lines.append(f"### `{t.file_path}`\n")
        for fn in t.test_functions:
            lines.append(f"- `{fn}`")
        lines.append("")

    lines.append("## Notes\n")
    lines.append("This file is generated by repo-brain. Do not manually edit.")
    lines.append(f"\nGenerated at: {repo_map.scan_timestamp}")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out
